{{- if and .Values.dapr.enabled .Values.dapr.pubsub.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ printf "%s-%s" (include "todo-app.fullname" .) "pubsub" | trunc 50 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.dapr.pubsub.redisHost | quote }}
  - name: redisPassword
    secretKeyRef:
      name: {{ .Values.dapr.pubsub.secretName }}
      key: {{ .Values.dapr.pubsub.secretKey }}
  - name: consumerID
    value: "{{ .Release.Name }}-consumer"
  - name: enableTLS
    value: "false"
  scopes:
  - {{ include "todo-app.fullname" . }}-backend
{{- end }}