{{- if and .Values.dapr.enabled .Values.dapr.stateStore.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ printf "%s-%s" (include "todo-app.fullname" .) "statestore" | trunc 50 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.dapr.stateStore.redisHost | quote }}
  - name: redisPassword
    secretKeyRef:
      name: {{ .Values.dapr.stateStore.secretName }}
      key: {{ .Values.dapr.stateStore.secretKey }}
  - name: actorStateStore
    value: "false"
  - name: enableTLS
    value: "false"
  scopes:
  - {{ include "todo-app.fullname" . }}-backend
{{- end }}